plugin:
  generic-crd-plugin:
    image: ghcr.io/loft-sh/vcluster-generic-crd-plugin:latest
    imagePullPolicy: IfNotPresent
    rbac:
      # extra namespaced permissions required for this plugin configuration
      role:
        extraRules:
          - apiGroups: ["networking.istio.io"]
            resources: ["virtualservices", "destinationrules", "gateways", "serviceentries"]
            verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
          - apiGroups: ["traefik.io"]
            resources: ["ingressroutes", "ingressroutetcps", "ingressrouteudps"]
            verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
          - apiGroups: [""]
            resources: ["services/status"]
            verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]           
      # extra cluster scoper permissions required for the plugin
      clusterRole:
        extraRules:
          - apiGroups: ["apiextensions.k8s.io"]
            resources: ["customresourcedefinitions"]
            verbs: ["get", "list", "watch"]
    env:
      - name: CONFIG
        value: |-
          version: v1beta1
          mappings: 
            - fromHostCluster:
                apiVersion: traefik.io/v1alpha1
                kind: IngressRoute
              fromVirtualCluster:
                apiVersion: traefik.io/v1alpha1
                kind: IngressRoute                                 
            - fromHostCluster:  
                apiVersion: traefik.io/v1alpha1
                kind: IngressRouteTCP
              fromVirtualCluster:
                apiVersion: traefik.io/v1alpha1
                kind: IngressRouteTCP                   
            - fromHostCluster:  
                apiVersion: traefik.io/v1alpha1
                kind: IngressRouteUDP
              fromVirtualCluster:
                apiVersion: traefik.io/v1alpha1
                kind: IngressRouteUDP
            # - fromHostCluster:
            #     apiVersion: v1
            #     kind: Service
            #   fromVirtualCluster:
            #     apiVersion: v1
            #     kind: Service
            #     patches:
            #       - op: rewriteLabelSelector
            #         path: .spec.selector                                  


