plugin:
  generic-crd-plugin:
    image: ghcr.io/loft-sh/vcluster-generic-crd-plugin:latest
    imagePullPolicy: IfNotPresent
    rbac:
      role:
        extraRules:
          - apiGroups: ["networking.istio.io"]
            resources: ["virtualservices", "destinationrules", "gateways", "serviceentries"]
            verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
          - apiGroups: ["traefik.io"]
            resources: ["ingressroutes", "ingressroutetcps", "ingressrouteudps"]
            verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]       
      clusterRole:
        extraRules:
          - apiGroups: ["apiextensions.k8s.io"]
            resources: ["customresourcedefinitions"]
            verbs: ["get", "list", "watch"]
    env:
      - name: CONFIG
        value: |-
          version: v1beta1
          mappings: 
            - fromVirtualCluster:
                apiVersion: traefik.io/v1alpha1
                kind: IngressRoute
                patches:
                  - op: rewriteName
                    path: .spec.routes[*].services[*].name
                reversePatches:
                  - op: copyFromObject
                    fromPath: status
                    path: status                                                                          
            - fromHostCluster:  
                apiVersion: traefik.io/v1alpha1
                kind: IngressRouteTCP
              fromVirtualCluster:
                apiVersion: traefik.io/v1alpha1
                kind: IngressRouteTCP                   
            - fromHostCluster:  
                apiVersion: traefik.io/v1alpha1
                kind: IngressRouteUDP
              fromVirtualCluster:
                apiVersion: traefik.io/v1alpha1
                kind: IngressRouteUDP

